name: 'hubspot'
version: '1.0.0'
config-version: 2

vars:
  hubspot:
    email_event_bounce: "{{ ref('stg_hubspot__email_event_bounce') }}"
    email_event_click: "{{ ref('stg_hubspot__email_event_click') }}"
    email_event_deferred: "{{ ref('stg_hubspot__email_event_deferred') }}"
    email_event_delivered: "{{ ref('stg_hubspot__email_event_delivered') }}"
    email_event_dropped: "{{ ref('stg_hubspot__email_event_dropped') }}"
    email_event_forward: "{{ ref('stg_hubspot__email_event_forward') }}"
    email_event_open: "{{ ref('stg_hubspot__email_event_open') }}"
    email_event_print: "{{ ref('stg_hubspot__email_event_print') }}"
    email_event_sent: "{{ ref('stg_hubspot__email_event_sent') }}"
    email_event_spam_report: "{{ ref('stg_hubspot__email_event_spam_report') }}"
    email_event_status_change: "{{ ref('stg_hubspot__email_event_status_change') }}"
    email_event: "{{ ref('stg_hubspot__email_event') }}"

models:
  hubspot:
    +materialized: table
    email_events:
      +materialized: ephemeral
    intermediate:
      +materialized: ephemeral